import type { NextPage } from "next";
import Head from "next/head";
import { Counter } from "../components/Counter";
import useSWR from "swr";

import TopN from "../components/TopNCases"

interface GlobalData {
  confirmed: {
    detail: string;
    value: number;
  };
  countryDetail: {
    pattern: string;
    example: string;
  };
  dailySummary: string;
  dailyTimeSeries: {
    pattern: string;
    example: string;
  };
  deaths: {
    detail: string;
    value: number;
  };
  image: string;
  lastUpdate: Date;
  recovered: {
    detail: string;
    value: number;
  };
  source: string;
}

const Home: NextPage = () => {
  const fetcher = (url: string) => fetch(url).then((res) => res.json());
  const { data, error } = useSWR("https://covid19.mathdro.id/api", fetcher, {
    refreshInterval: 1000,
  });

  if (!data) {
    return <div>Loading....</div>;
  }

  const globalData: GlobalData = data;

  return (
    <div>
      <Head>
        <title>Salabite - COVID-19 Statistics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-center font-bold text-white text-4xl my-4 italic">
        Wear your mask 😷! 
      </h1>

      {/* Global */}
      <section className="w-full">
        <div className="grid gap-4 lg:grid-cols-3 lg:grid-rows-1">
          <div className="bg-gray-400 shadow-md shadow-gray-500 p-4 mx-4">
            <div className="font-bold text-xl">Confirmed</div>
            <div className="font-black text-4xl text-right">
              <Counter from={0} to={globalData.confirmed.value} />
            </div>
          </div>
          <div className="bg-green-400 shadow-md shadow-gray-500 p-4 mx-4">
            <div className="font-bold text-xl">Recovered</div>
            <div className="font-black text-4xl text-right">
              <Counter from={0} to={globalData.recovered.value} />
            </div>
          </div>
          <div className="bg-red-400 shadow-md shadow-gray-500 p-4 mx-4">
            <div className="font-bold text-xl">Deaths</div>
            <div className="font-black text-4xl text-right">
              <Counter from={0} to={globalData.deaths.value} />
            </div>
          </div>
        </div>
      </section>

      {/* Top 20 */}
      <TopN />
    </div>
  );
};

export default Home;
